spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/wutong-user?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  redis:
    jedis:
      pool:
        max-idle: 10
        max-active: 10
        max-wait: -1
    host: 127.0.0.1
    port: 6379
    timeout: 2000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env: bus
